---
kind: Pod 
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
    - name: c01
      image: httpd
      ports:
       - containerPort: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
   name: testpod 
spec:
   replicas: 1
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     name: deployment
   template:
     metadata:
       name: testpod1
       labels:
         name: deployment
     spec:
      containers:
        - name: c00
          image: httpd
          ports:
          - containerPort: 80
---
kind: Service                             # Defines to create Service type Object
apiVersion: v1
metadata:
  name:  testpod 
spec:
  ports:
    - port: 80                               # Containers port exposed
      targetPort: 80                     # Pods port
  selector:
    name: deployment                    # Apply this service to any pods which has the specific label
  type: NodePort  
                # Specifies the service type i.e ClusterIP or NodePort
---

kind: ReplicationController               
apiVersion: v1
metadata:
  name: testpod
spec:
  replicas: 2            
  selector:        
    myname: deployment                             
  template:                
    metadata:
      name: testpod
      labels:            
        myname: deployment
    spec:
     containers:
       - name: c01
         image: httpd
         command: ["/bin/bash", "-c", "while true; do echo Hello-Bhupinder; sleep 5 ; done"]
---
kind: Service                             # Defines to create Service type Object
apiVersion: v1
metadata:
  name:  testpod 
spec:
  ports:
    - port: 80                               # Containers port exposed
      targetPort: 80                     # Pods port
  selector:
    name: deployment                    # Apply this service to any pods which has the specific label
  type: LoadBalancer  
